---
language: ruby
script:
  - chmod -R a+x bin/
  - bin/rubocop
  - bin/foodcritic .
  - bin/rspec
rvm:
  - 2.1
  - 2.2
branches:
  only:
    - master
builder_args: --jobs 7
matrix:
  fast_finish: true
